# main text of home
title: Simon Liu
bio: medical student | biomedical engineer | data scientist & archivist

# twitter summary info
description: Fixing the world one project at a time

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile_optimized.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: true

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://simonliu.dev/cv/

url: https://simonliu.dev
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: simonliu-dev # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
linkedin: simonliu99
github: simonliu99
email: simon+website@simonliu.dev
orcid: 0000-0002-1182-5492
google-scholar: https://scholar.google.com/citations?user=fwh_UDMAAAAJ&hl=en

authors:
  simonliu:
    name: Simon Liu
    bio: medical student & biomedical engineer
    external-image: false
    picture: assets/images/profile.png
    twitter: michaelblob
  # jamesfoster:
  #   name: James Foster
  #   bio: A Man who develops software with coffee
  #   external-image: false
  #   picture: assets/images/james.jpg
  #   twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji


compress_html:
  ignore:
    envs:
      - development
      - stage
include:
  - files
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
